name: docker-deploy
on: [push, workflow_dispatch]
jobs:
  deploy:
    name: "Deploy on server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Stop and update
        run: ssh staging 'cd /home/ubuntu/applications/ingestify/ingestify && docker compose down && git pull'

      - name: Build and start
        run: ssh staging 'cd /home/ubuntu/applications/ingestify/ingestify/ingestify && quarkus build && cd .. && docker compose up -d'
